name: "Sends Whatsapp messages for various event Actions for Github"
author: "Glennpedley"
description: "Various events triggers a notification to be sent to Whatsapp"
branding:
  icon: message-circle
  color: black
  
inputs:
  pr_number:
    description: 'Pull Request Number'
    default: ${{ github.event.pull_request.number }}
  pr_title:
    description: 'Pull Request Title'
    default: ${{ github.event.pull_request.title }}
  pr_body:
    description: 'Pull Request Content'
    default: ${{ github.event.pull_request.body }}
  issue_title: 
    description: 'Issue Title'
    default: ${{ github.event.issue.title }}
  issue_number:
    description: 'Issue Number'
    default: ${{ github.event.issue.number }}
  issue_body:
    description: 'Issue Body'
    default: ${{ github.event.issue.body }}
  repo_fork_count:
    description: 'Number of Forks'
    default: ${{ github.event.repository.forks_count }}
  repo_watch_count:
    description: 'Number of Watch'
    default: ${{ github.event.repository.watchers_count }}

runs:
  using: "docker"
  image: "Dockerfile"
